# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Debug: List files in /app directory
RUN ls -la /app

# Debug: List files in /app/node_modules directory
RUN ls -la /app/node_modules

# Copy the rest of the application code
COPY . .

# Expose port 5001
EXPOSE 5001

# Define the command to run the application
CMD ["node", "server.js"]
