apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unbooked-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/stewwratt/unbooked2024.git"
    path: infrastructure/k8s
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
